services:
  postgres:
    image: postgres:16-alpine
    container_name: three_focus_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - three_focus_net

volumes:
  postgres_data:

networks:
  three_focus_net:
    name: three_focus_net
