ALTER TABLE users
    ADD COLUMN name         VARCHAR(50)  NOT NULL DEFAULT '',
    ADD COLUMN phone        VARCHAR(20)  NOT NULL DEFAULT '',
    ADD COLUMN gender       VARCHAR(10)  NOT NULL DEFAULT 'OTHER',
    ADD COLUMN birthday     DATE         NOT NULL DEFAULT '1900-01-01',
    ADD COLUMN terms_agreed BOOLEAN      NOT NULL DEFAULT FALSE;
